{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/1.0.0/shared-1.0.0.module",
    "group": "com.corecmp",
    "module": "shared",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "shared-jvm-1.0.0.jar",
          "url": "shared-jvm-1.0.0.jar",
          "size": 1613111,
          "sha512": "c826089a62bae5b0b82139bf0c7347d993fdfdf99230cf00d07c7acea0c033f3d1dc3ff4e0ec0535087fe1ebef3e90965ab1297fd98878c485760d639dfa7079",
          "sha256": "e2cb5fc8c616c315babb4d9acee69453e2a3ec377cc381adaba1f5051159c3be",
          "sha1": "e9e19ff4bfb74c676e11087fe56217220b12d531",
          "md5": "7b840ad612cbb15c51873ad9aa4ac501"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "compottie",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-beta05"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "coroutines-extensions",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.sarxos",
          "module": "webcam-capture",
          "version": {
            "requires": "0.3.12"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-driver",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "shared-jvm-1.0.0.jar",
          "url": "shared-jvm-1.0.0.jar",
          "size": 1613111,
          "sha512": "c826089a62bae5b0b82139bf0c7347d993fdfdf99230cf00d07c7acea0c033f3d1dc3ff4e0ec0535087fe1ebef3e90965ab1297fd98878c485760d639dfa7079",
          "sha256": "e2cb5fc8c616c315babb4d9acee69453e2a3ec377cc381adaba1f5051159c3be",
          "sha1": "e9e19ff4bfb74c676e11087fe56217220b12d531",
          "md5": "7b840ad612cbb15c51873ad9aa4ac501"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "shared-jvm-1.0.0-sources.jar",
          "url": "shared-jvm-1.0.0-sources.jar",
          "size": 188066,
          "sha512": "ca79ce6089eb01caae571b778b43cfc6dd1c79907d7a7e7eb5bef9f01778b6533a44c3c7142e5bc9739dfef27cea3294292f33552dd86bbc051d3cd4ab6a9a62",
          "sha256": "006813120f33b63a8f9dcb7ca45acb808709b8baf312631a40c9141d1da623b6",
          "sha1": "ada328ea45ad186351f29e3245a0468c414ea3c5",
          "md5": "4dbe52306458e628ed0977bf0041fe7c"
        }
      ]
    }
  ]
}
